ncl:
  ncl_lib: "/g1/u/nwp_pd/GRAPH/ncllib/"
  geodiag_root: "/g1/u/nwp_pd/GEODIAG/"
  load_env_script: "./load_ncl_env.sh"

python:
  load_env_script: "./load_python_env.sh"

general:
  run_base_dir: "${JOBDIR}/graphics"

config:
  systems_dir: "./systems"