system:
  script_dir: "/home/wangdp/project/graphics/operation/system/NWP_GRAPES_MESO_3KM_GRAPH/graph/script"

ncl:
  ncl_lib: "/home/wangdp/project/graphics/operation/system/NWP_GRAPES_MESO_3KM_GRAPH/graph/script/nclib"

components:
  meso_3km:
    system:
      script_dir: "/home/wangdp/project/graphics/operation/system/NWP_GRAPES_MESO_3KM_POST/tograph/script"
