system:
  script_dir: "/g1/u/op_post/OPER/ECFLOW/system/cma_meso_1km_post/base/CMA_MESO_1KM_POST/graph/script"

ncl:
  ncl_lib: "/g1/u/op_post/OPER/ECFLOW/system/cma_meso_1km_post/base/CMA_MESO_1KM_POST/graph/script/nclib"

components:
  meso_3km:
    system:
      script_dir: "/g1/u/op_post/OPER/ECFLOW/system/cma_meso_1km_post/base/CMA_MESO_1KM_POST/script"