system:
  script_dir: "/some/path/NWP_GRAPES_MESO_3KM_GRAPH/graph/script"

ncl:
  ncl_lib: "/some/path/NWP_GRAPES_MESO_3KM_GRAPH/graph/script/nclib"

components:

  # for meso 3km graph displaying in NWPC/CMA
  meso_3km:
    system:
      script_dir: "/some/path/NWP_GRAPES_MESO_3KM_POST/tograph/script"